### ISSUE TITLE
Donor edits the pledge amount 

### ISSUE THREAD

**Issue by nshamit** [LSFLK/MedicinesforLK#154]
- [ ] Donor edits the pledge amount e.g. First pledged $7,500. Then wants to go back in and pledge a higher amount, say $10,000. 

Workflow:
- Donor goes to My pledges
- Donor clicks on an aid package already pledged to
- Donor sees Edit button 
- Once pledge amount is typed in, donor can click on Update button

![Screen Shot 2022-07-12 at 19 05 26](https://user-images.githubusercontent.com/44461004/178502832-187cd02e-de68-48cb-8c75-90243c8df0f4.jpg)

**Comment by jayasanka-sack** [comment]
@anupama-pathirage It seems there's no endpoint to get a pledge by `donorID` AND `aidPackageID` 

Could you please check it?

**Comment by jayasanka-sack** [comment]
Thanks @AmilaJ !

**Comment by jayasanka-sack** [comment]
We need the following as well,

1. GET /{donorID}/aidpackages/{packageID} 
We don't need this API because the page is public. It should be `/aidpackages/{packageID}` instead.
2. All aid package resources on the donor API should not send draft aid packages to the client. 

btw, `/{donorID}/aidpackages/{packageID}/pleges` is sending an array. Since a donor can have one pledge per package, it should be an object, right?

**Comment by Gravewalker666** [comment]
> btw, /{donorID}/aidpackages/{packageID}/pleges is sending an array. Since a donor can have one pledge per package, it should be an object, right?

Yeah, it should be, on the frontend I wrote the code to get the zeroth element on the array for now.
