### ISSUE TITLE
When the status of an aid package is changed, the screen goes blank

### ISSUE THREAD

**Issue by nshamit** [LSFLK/MedicinesforLK#290]
- [ ] When the status of an aid package is changed, the screen goes blank
![Screen Shot 2022-07-28 at 10 58 01](https://user-images.githubusercontent.com/44461004/181427709-5bced213-9af9-457c-aaf1-8d2e6d7c918d.jpg)

- [ ] Checking the status of pledges made also makes the screen go blank. 
To reproduce:
1. Login as a donor, and pledge against an aid package
2. Login as an admin and check the pledge status

**Comment by kanushka** [comment]
## RCA

The issue was that the AidPackage update API doesn't send supplier information in the quotation field. Because of that OrderItemsTable failed to render `supplier` and `period` information.

![image](https://user-images.githubusercontent.com/24244523/181470428-64397db4-c73d-4756-8e71-0e3b5a6feee9.png)


But AidPackage get API has supplier information

![image](https://user-images.githubusercontent.com/24244523/181470313-006bf417-b04c-4ec5-a916-e90037c6eeb7.png)

### Suggestion

Updating AidPackage PATCH API will fix this issue.

**Comment by kanushka** [comment]
@anupama-pathirage

**Comment by kanushka** [comment]
Without changing BE API, I have to update the FE logic to fix this issue.
