### ISSUE TITLE
Invalid CSV length in line 2 of Master Needs tab in Medical Needs sheet. Error also in Supply Quotation page 

### ISSUE THREAD

**Issue by nshamit** [LSFLK/MedicinesforLK#460]
- [ ] Prod environment: Cannot upload the CSV files downloaded from the Master Needs tab. I get an error message:

![Screen Shot 2022-09-07 at 10 02 23](https://user-images.githubusercontent.com/44461004/188789534-71567e3a-0376-4d3e-a256-532ff5017942.jpg)

To reproduce:
1. Download CSV from Master Needs tab
2. Upload in the Needs uploader of admin portal (production environment). 
3. Receive error message: Invalid CSV length in line 2.
Note: I cannot make any changes to line 2 of the Master Needs tab.

**Comment by nshamit** [comment]
In Supply Quotation page, we get this error: Invalid csv length in line 1:

![Screen Shot 2022-09-07 at 10 08 36](https://user-images.githubusercontent.com/44461004/188790019-011ddb04-df0d-4b1d-b74e-4104e870b61d.jpg)

**Comment by akbandara** [comment]
Do these same CSV files fail in development environment?

**Comment by nshamit** [comment]
Yes, I receive the same errors in the dev environment as well.

**Comment by akbandara** [comment]
I think I have diagnosed the issue after looking at the Ballerina code that processes the CSV (https://github.com/LSFLK/MedicinesforLK-AdminAPI/blob/main/csv_processor.bal). 

Looking at the ‘createQuotationFromCSVData’ and ‘createMedicalNeedsFromCSVData’ functions, I think the issue is because we changed the columns in the CSV to include the extra fields as follows:
Master Needs - now includes a column for ‘Item Type’
Supplier Quotation - now includes columns for ‘Item Type’ and ‘Unit’

Generated CSVs have the following columns:

**Needs:** LookUpIndex2, sum Quantity Needed Number of unit needed,Urgency,Period,Hospital / Beneficiary Institution,Item Name,Type,Unit,Total Qty Needed

**Quotations:** Supplier,Item Needed,Item Type (Auto fill),Item Unit (Auto fill),Drug Registration Description,Brand Name,Period,Available Qty,Expiry Date,CIFValue

@manuranga - Ballerina code needs to be modified to match this CSV format.

**Comment by nshamit** [comment]
#370
