### ISSUE TITLE
Time stamp on donor portal showing 1970 for YYYY while on the admin portal side, the time stamp is showing correctly. 

### ISSUE THREAD

**Issue by nshamit** [LSFLK/MedicinesforLK#465]
- [ ] Time stamp on donor portal showing 1970 for YYYY while on the admin portal side, the time stamp is showing correctly. 
![Screen Shot 2022-09-07 at 12 24 19](https://user-images.githubusercontent.com/44461004/188809567-eafcf53c-abaa-489d-be3a-a3d91643633c.jpg)

![Screen Shot 2022-09-07 at 12 25 31](https://user-images.githubusercontent.com/44461004/188809766-7b10c34e-10d2-4631-989c-23e929cad6d3.jpg)

**Comment by dinuka-rp** [comment]
@anjula-sack I can take this up if u haven't already applied a fix

**Comment by anjula-sack** [comment]
> @anjula-sack I can take this up if u haven't already applied a fix

I don't think this is an issue. It's only on prod. and in the code, we are formatting the UNIX timestamp. maybe you can give a try as well.

**Comment by dinuka-rp** [comment]
The issue is in the backend @manuranga @nshamit 

dateTime is received as null. It's sending the datetime in a DB/ Ballerina format. I'm guessing this is the object/ struct used to hold the date by Ballerina.
![image](https://user-images.githubusercontent.com/47103883/190171382-5ca6148b-9054-45d5-a980-586cae945ba3.png)

A frontend validation can be added to not display the _dateTime_ if it's _null_, but it definitely has to be received from my understanding as this dateTime is recorded in the backend.

**Comment by dinuka-rp** [comment]
@manuranga would be great if u could look into this/ assign someone from the BE team
