### ISSUE TITLE
Custom package image is not shown on 'My pledges' tab of Donate page

### ISSUE THREAD

**Issue by akbandara** [LSFLK/MedicinesforLK#539]
**Is your feature request related to a problem? Please describe.**
In the Donor Portal, when a aid package is assigned a custom image, this is not shown in the 'My pledges' tab of the Donate page. This is shown in the two screenshots below, where the first shows the aid package on the 'Goal pending' tab and the second shows the same package on the 'My pledges' tab.

<img width="80%" alt="Screenshot 2022-10-15 at 21 33 21" src="https://user-images.githubusercontent.com/3705261/196006564-820b5882-06a1-45f1-addf-63140f8127d2.png">

<img width="80%" alt="Screenshot 2022-10-15 at 21 33 30" src="https://user-images.githubusercontent.com/3705261/196006569-1e8e6f39-a9a1-4f06-b3ea-9b90bfa6fb52.png">

**Describe the solution you'd like**
The custom image for a package should be shown on all tabs where the package is shown.

**Comment by dinuka-rp** [comment]
I can't seem to reproduce this error as the API isn't returning the aidpackages created by my account. Maybe it's because some Asgardeo changes were done over the last couple of days? @manuranga 

@akbandara all 3 tabs are using the same component, therefore it should ideally show the same image. Not too sure why it's not showing up here. Maybe the API for fetching aid packages by donor doesn't return the thumbnail image.
